name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js with improved caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      # Run tests before other steps
      - name: Run Tests
        run: npm run test
        
      # Run linter to check code quality
      - name: Run Linter
        run: npm run lint

      - name: Check Build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run build

      # Supabase CLI version check
      - name: Check Supabase CLI Version
        run: npx supabase --version
        
      # Supabase deployment steps
      - name: Link Supabase Project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          YOUR_PROJECT_REF: ${{ secrets.YOUR_PROJECT_REF }}
        run: |
          echo "Linking to Supabase project: $YOUR_PROJECT_REF"
          npm run supabase:link -- --project-ref $YOUR_PROJECT_REF --password $SUPABASE_DB_PASSWORD

      # Deploy database with debug mode for detailed error output
      - name: Deploy Database Migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          YOUR_PROJECT_REF: ${{ secrets.YOUR_PROJECT_REF }}
        run: |
          echo "Running database push with debug mode"
          # Attempt with debug mode to get more details on errors
          npx supabase db push --debug || {
            echo "Database push failed with debug mode. Trying with password entered manually..."
            # Try an alternative approach with password specified directly
            echo "$SUPABASE_DB_PASSWORD" | npx supabase db push
          }

      # Enhanced Supabase Functions Deployment
      - name: Deploy Supabase Functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          # List existing functions for logging
          echo "Listing deployed functions:"
          npm run supabase:functions:list
          
          # Deploy all functions
          echo "Deploying all functions:"
          npm run supabase:functions:deploy
          
          # Or deploy specific functions if needed
          # echo "Deploying hello-world function:"
          # npm run supabase:functions:deploy:hello-world
          
          # Verify functions were deployed
          echo "Verifying deployed functions:"
          npm run supabase:functions:list
        
      # Vercel deployment steps
      - name: Pull Vercel Environment Information
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: |
          export NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
          export NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
          npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}


